# Generated by Django 4.0.8 on 2022-12-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bars',
            fields=[
                ('bar_id', models.AutoField(primary_key=True, serialize=False)),
                ('bar_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Beers',
            fields=[
                ('beer_id', models.AutoField(primary_key=True, serialize=False)),
                ('beer_name', models.CharField(max_length=500)),
                ('bar', models.CharField(max_length=500)),
                ('dateofcreation', models.DateField()),
                ('photo', models.CharField(max_length=500)),
            ],
        ),
    ]
